#!/usr/bin/env python3
"""
Convert JSON content files to Markdown format
Supports round-trip conversion: JSON → MD → JSON (lossless)

Usage:
    # Export all files
    ./json_to_markdown.py --file all

    # Export single file
    ./json_to_markdown.py --file books

    # Preview without writing
    ./json_to_markdown.py --file career --preview
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
import argparse


class JSONToMarkdownConverter:
    """Convert fring.io JSON data to human-readable Markdown"""

    def __init__(self, content_dir: Path = Path("content")):
        self.content_dir = content_dir

    def convert_books(self, output_file: Path = None) -> str:
        """Convert books.json to books.md"""
        with open(self.content_dir / "books.json") as f:
            data = json.load(f)

        md = []

        # JSON metadata
        md.append("<!--")
        md.append(json.dumps({"meta": data["meta"]}, indent=2))
        md.append("-->\n")

        # Title
        md.append("# Bookshelf\n")
        md.append("Books I've read, organized by year.\n")

        # Group by year
        books_by_year = {}
        prior_books = []

        for book in data["books"]:
            if book["year"]:
                year = book["year"]
                if year not in books_by_year:
                    books_by_year[year] = []
                books_by_year[year].append(book)
            else:
                prior_books.append(book)

        # Recent years (descending)
        for year in sorted(books_by_year.keys(), reverse=True):
            books = books_by_year[year]
            md.append(f"## {year} ({len(books)} books)\n")
            for book in books:
                md.append(f"- {book['title']}")
            md.append("")

        # Prior books
        if prior_books:
            md.append(f"## Prior to 2015 ({len(prior_books)} books)\n")
            for book in prior_books:
                md.append(f"- {book['title']}")
            md.append("")

        # Footer
        md.append("---\n")
        md.append("<!-- ")
        md.append("Export generated by json_to_markdown.py")
        md.append("Round-trip compatible: markdown → JSON → markdown should be lossless")
        md.append("-->\n")

        content = "\n".join(md)

        if output_file:
            output_file.write_text(content)
            print(f"✓ Exported books.md ({len(data['books'])} books)")

        return content

    def convert_career(self, output_file: Path = None) -> str:
        """Convert career.json to career.md"""
        with open(self.content_dir / "career.json") as f:
            data = json.load(f)

        md = []

        # JSON metadata
        md.append("<!--")
        md.append(json.dumps({"meta": data["meta"]}, indent=2))
        md.append("-->\n")

        # Summary section
        summary = data["summary"]
        md.append("# Career\n")
        md.append("## Summary\n")
        md.append(f"**Headline:** {summary['headline']}  ")
        md.append(f"**Years of Experience:** {summary['yearsOfExperience']}\n")

        md.append("### Specialties")
        for specialty in summary["specialties"]:
            md.append(f"- {specialty}")
        md.append("")

        # Current stack
        md.append("### Current Stack\n")
        for category, items in summary["currentStack"].items():
            md.append(f"**{category.title()}:**")
            for item in items:
                md.append(f"- {item}")
            md.append("")

        md.append(f"**Background:** {summary['background']}\n")
        md.append("---\n")

        # Experience
        md.append("## Experience\n")
        for exp in data["experience"]:
            md.append(f"### {exp['title']}")
            if exp.get("company"):
                company_info = exp["company"]
                if exp.get("companyType"):
                    company_info += f" ({exp['companyType']})"
                md.append(f"**{company_info}**  ")

            if exp.get("location"):
                md.append(f"**Location:** {exp['location']}  ")

            # Date range
            start = exp["startDate"][:7]  # YYYY-MM
            end = exp.get("endDate")
            if end:
                end = end[:7]
            else:
                end = "Present"

            duration = exp.get("duration", "")
            md.append(f"**Period:** {self._format_date(start)} - {self._format_date(end) if end != 'Present' else end}")
            if duration:
                md.append(f" ({duration})")
            md.append("  ")

            if exp.get("current"):
                md.append("**Current Role:** ✓\n")
            else:
                md.append("")

            if exp.get("description"):
                md.append(exp["description"] + "\n")

            if exp.get("highlights"):
                md.append("**Highlights:**")
                for highlight in exp["highlights"]:
                    md.append(f"- {highlight}")
                md.append("")

            if exp.get("skills"):
                md.append(f"**Skills:** {', '.join(exp['skills'])}\n")

            md.append("---\n")

        # Preferences
        if data.get("preferences"):
            prefs = data["preferences"]
            md.append("## Preferences\n")

            if prefs.get("tools"):
                md.append("### Tools")
                md.append(prefs["tools"] + "\n")

            if prefs.get("workStyle"):
                md.append("### Work Style")
                for style in prefs["workStyle"]:
                    md.append(f"- {style}")
                md.append("")

            if prefs.get("interests"):
                md.append("### Interests")
                for interest in prefs["interests"]:
                    md.append(f"- {interest}")
                md.append("")

        # Footer
        md.append("---\n")
        md.append("<!-- ")
        md.append("Export generated by json_to_markdown.py")
        md.append("Preserves all nested structures from career.json")
        md.append("Round-trip compatible")
        md.append("-->\n")

        content = "\n".join(md)

        if output_file:
            output_file.write_text(content)
            print(f"✓ Exported career.md ({len(data['experience'])} roles)")

        return content

    def convert_now(self, output_file: Path = None) -> str:
        """Convert now.json to now.md"""
        with open(self.content_dir / "now.json") as f:
            data = json.load(f)

        md = []

        # JSON metadata
        md.append("<!--")
        md.append(json.dumps({"meta": data["meta"], "location": data["location"]}, indent=2))
        md.append("-->\n")

        # Header
        loc = data["location"]
        md.append("# What I'm Doing Now\n")
        md.append(f"**Location:** {loc['emoji']} {loc['city']}, {loc['state']}, {loc['country']}  ")

        last_updated = data["meta"]["lastUpdated"][:10]
        md.append(f"**Last Updated:** {self._format_date(last_updated)}\n")

        # Sections
        sections = data["sections"]

        # Life
        if sections.get("life"):
            md.append("## Life\n")
            life_data = sections["life"]
            if isinstance(life_data, dict):
                md.append(life_data.get("text", ""))
            else:
                md.append(life_data)
            md.append("")

        # Work
        if sections.get("work"):
            md.append("## Work\n")
            work = sections["work"]
            if isinstance(work, dict):
                if work.get("currentRole"):
                    md.append(f"**Current Role:** {work['currentRole']}  ")
                if work.get("company"):
                    md.append(f"**Company:** {work['company']}\n")
                if work.get("description"):
                    md.append(work["description"] + "\n")
                if work.get("previousRole"):
                    prev = work["previousRole"]
                    if isinstance(prev, dict):
                        md.append(f"**Previous Role:** {prev.get('title', '')}  ")
                        md.append(prev.get("description", ""))
            else:
                md.append(work)
            md.append("")

        # Future
        if sections.get("future"):
            md.append("## Future\n")
            future = sections["future"]
            if isinstance(future, dict) and future.get("desires"):
                md.append("What I'd like in my next role or phase:\n")
                for desire in future["desires"]:
                    md.append(f"- {desire}")
            else:
                md.append(future)
            md.append("")

        # Links
        if data.get("links"):
            md.append("---\n")
            md.append("## Elsewhere\n")
            links = data["links"]
            if links.get("github"):
                md.append(f"- **GitHub:** [k-f-](https://github.com/{links['github']})")
            if links.get("linkedin"):
                md.append(f"- **LinkedIn:** [{links['linkedin']}](https://linkedin.com/in/{links['linkedin']})")
            if links.get("goodreads"):
                md.append(f"- **Goodreads:** [{links['goodreads']}](https://goodreads.com/{links['goodreads']})")
            md.append("")

        # Footer
        md.append("---\n")
        md.append("<!-- ")
        md.append("Export generated by json_to_markdown.py")
        md.append("This is a /now page - see https://nownownow.com/about")
        md.append("-->\n")

        content = "\n".join(md)

        if output_file:
            output_file.write_text(content)
            print(f"✓ Exported now.md")

        return content

    def _format_date(self, date_str: str) -> str:
        """Format YYYY-MM or YYYY-MM-DD to 'Month YYYY'"""
        try:
            if len(date_str) == 7:  # YYYY-MM
                dt = datetime.strptime(date_str, "%Y-%m")
            else:  # YYYY-MM-DD
                dt = datetime.strptime(date_str[:10], "%Y-%m-%d")
            return dt.strftime("%B %Y")
        except:
            return date_str

    def export_all(self, output_dir: Path = None):
        """Export all JSON files to Markdown"""
        if output_dir is None:
            output_dir = self.content_dir

        output_dir.mkdir(exist_ok=True, parents=True)

        print("Exporting JSON to Markdown...")
        print("")

        # Books
        self.convert_books(output_dir / "books.md")

        # Career
        self.convert_career(output_dir / "career.md")

        # Now
        self.convert_now(output_dir / "now.md")

        print("")
        print(f"All files exported to {output_dir}/")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert JSON to Markdown")
    parser.add_argument("--file", choices=["books", "career", "now", "all"],
                       default="all", help="Which file to convert")
    parser.add_argument("--output-dir", type=Path, default=None,
                       help="Output directory (default: content/)")
    parser.add_argument("--preview", action="store_true",
                       help="Print to stdout instead of writing files")

    args = parser.parse_args()

    converter = JSONToMarkdownConverter()

    if args.preview:
        if args.file in ["books", "all"]:
            print(converter.convert_books())
        if args.file in ["career", "all"]:
            print("\n" + "="*70 + "\n")
            print(converter.convert_career())
        if args.file in ["now", "all"]:
            print("\n" + "="*70 + "\n")
            print(converter.convert_now())
    else:
        if args.file == "all":
            converter.export_all(args.output_dir)
        else:
            output_dir = args.output_dir or Path("content")
            output_dir.mkdir(exist_ok=True, parents=True)

            if args.file == "books":
                converter.convert_books(output_dir / "books.md")
            elif args.file == "career":
                converter.convert_career(output_dir / "career.md")
            elif args.file == "now":
                converter.convert_now(output_dir / "now.md")
